// Datos de ejemplo para la aplicación

// Lista de profesores disponibles
export const profesoresList = [
  "Juan Pérez",
  "María Rodríguez",
  "Carlos Jiménez",
  "Ana Torres",
  "Roberto Sánchez",
  "Luisa Fernández",
  "Ricardo Mendoza",
  "Patricia Álvarez",
  "Fernando Gutiérrez",
  "Claudia Morales",
  "Javier Ramírez",
  "Gabriela Ortiz",
  "Alejandro Vargas",
  "Mónica Castro",
  "Eduardo Flores",
]

// Actividades de movilidad
export const mockActividades = [
  {
    id: "1",
    nombre: "Intercambio académico Universidad de Barcelona",
    alcance: "internacional",
    pais: "España",
    ciudad: "Barcelona",
    actividad: "Intercambio académico de un semestre para estudiantes de ingeniería",
    cantidadEstudiantes: "15",
    lugar: "Universidad de Barcelona",
    fechaInicio: new Date("2023-02-01"),
    fechaFin: new Date("2023-06-30"),
    instituciones: ["Universidad de Barcelona"],
    anio: "2023",
    semestre: "1",
    tipoMovilidad: "saliente",
    modalidad: "presencial",
    objeto: "Fortalecer competencias interculturales y conocimientos técnicos",
    profesorLider: "Juan Pérez",
    profesores: ["María Rodríguez"],
    apoyoFinanciero: "2500000",
    estudiantes: ["Ana García", "Carlos López", "Diana Martínez"],
    evidencias: ["https://ejemplo.com/fotos-barcelona", "Certificados de participación"],
  },
  {
    id: "2",
    nombre: "Pasantía empresarial Ecopetrol",
    alcance: "nacional",
    ciudad: "Bogotá",
    actividad: "Pasantía profesional en el área de ingeniería de procesos",
    cantidadEstudiantes: "8",
    lugar: "Sede principal Ecopetrol",
    fechaInicio: new Date("2023-07-15"),
    fechaFin: new Date("2023-12-15"),
    instituciones: ["Ecopetrol S.A."],
    anio: "2023",
    semestre: "2",
    tipoMovilidad: "saliente",
    modalidad: "presencial",
    objeto: "Aplicar conocimientos en entorno laboral real",
    profesorLider: "Roberto Sánchez",
    profesores: [],
    apoyoFinanciero: "800000",
    estudiantes: ["Pedro Ramírez", "Laura Gómez"],
    evidencias: ["Informes mensuales", "Evaluación de desempeño"],
  },
  {
    id: "3",
    nombre: "Curso virtual con MIT",
    alcance: "internacional",
    pais: "Estados Unidos",
    ciudad: "Cambridge",
    actividad: "Curso especializado en inteligencia artificial",
    cantidadEstudiantes: "25",
    lugar: "Plataforma virtual MIT",
    fechaInicio: new Date("2023-09-01"),
    fechaFin: new Date("2023-11-30"),
    instituciones: ["Massachusetts Institute of Technology"],
    anio: "2023",
    semestre: "2",
    tipoMovilidad: "entrante",
    modalidad: "virtual",
    objeto: "Actualización en tecnologías emergentes",
    profesorLider: "Carlos Jiménez",
    profesores: ["Ana Torres"],
    apoyoFinanciero: "1200000",
    estudiantes: ["Sofía Vargas", "Daniel Moreno"],
    evidencias: ["Certificados de finalización", "Proyectos finales"],
  },
  {
    id: "4",
    nombre: "Visita técnica planta de tratamiento",
    alcance: "local",
    actividad: "Visita guiada a planta de tratamiento de aguas residuales",
    cantidadEstudiantes: "30",
    lugar: "PTAR Municipal",
    fechaInicio: new Date("2024-03-10"),
    fechaFin: new Date("2024-03-10"),
    instituciones: ["Empresa de Acueducto Municipal"],
    anio: "2024",
    semestre: "1",
    tipoMovilidad: "saliente",
    modalidad: "presencial",
    objeto: "Conocer procesos de tratamiento de aguas residuales",
    profesorLider: "Luisa Fernández",
    profesores: [],
    apoyoFinanciero: "300000",
    estudiantes: ["Camila Rojas", "Andrés Suárez"],
    evidencias: ["Registro fotográfico", "Informe de visita"],
  },
  {
    id: "5",
    nombre: "Congreso Internacional de Ingeniería",
    alcance: "internacional",
    pais: "México",
    ciudad: "Ciudad de México",
    actividad: "Participación en congreso con ponencia de investigación",
    cantidadEstudiantes: "5",
    lugar: "Centro de Convenciones Banamex",
    fechaInicio: new Date("2024-04-15"),
    fechaFin: new Date("2024-04-20"),
    instituciones: ["Universidad Nacional Autónoma de México", "Asociación Internacional de Ingeniería"],
    anio: "2024",
    semestre: "1",
    tipoMovilidad: "saliente",
    modalidad: "presencial",
    objeto: "Presentar resultados de investigación y establecer contactos académicos",
    profesorLider: "Ricardo Mendoza",
    profesores: ["Patricia Álvarez"],
    apoyoFinanciero: "3500000",
    estudiantes: ["Juliana Castro", "Mauricio Ríos"],
    evidencias: ["Certificado de ponencia", "Memorias del congreso"],
  },
]

// Datos de estudiantes matriculados por semestre
export const mockMatriculados = {
  "2023-1": 1200,
  "2023-2": 1150,
  "2024-1": 1250,
}

// Función para obtener una actividad por ID
export const getActividadById = async (id: string) => {
  // Simula una llamada a API con un pequeño retraso
  return new Promise((resolve) => {
    setTimeout(() => {
      const actividad = mockActividades.find((act) => act.id === id)
      resolve(actividad || null)
    }, 500)
  })
}
